// Generated by https://quicktype.io

export interface Books {
    keys: Key[];
}

export interface Key {
    b: number;
    n: string;
    t: T;
    g: number;
}

export enum T {
    NT = 'NT',
    Ot = 'OT',
}
